export const MEXICAN_STATES = [
  "Aguascalientes",
  "Baja California",
  "Baja California Sur",
  "Campeche",
  "Chiapas",
  "Chihuahua",
  "Ciudad de México",
  "Coahuila",
  "Colima",
  "Durango",
  "Estado de México",
  "Guanajuato",
  "Guerrero",
  "Hidalgo",
  "Jalisco",
  "Michoacán",
  "Morelos",
  "Nayarit",
  "Nuevo León",
  "Oaxaca",
  "Puebla",
  "Querétaro",
  "Quintana Roo",
  "San Luis Potosí",
  "Sinaloa",
  "Sonora",
  "Tabasco",
  "Tamaulipas",
  "Tlaxcala",
  "Veracruz",
  "Yucatán",
  "Zacatecas",
] as const;

export const LEAD_STATUS_COLORS = {
  NEW: "bg-blue-100 text-blue-800",
  CONTACTED: "bg-yellow-100 text-yellow-800",
  FOLLOW_UP: "bg-orange-100 text-orange-800",
  AFFILIATED: "bg-green-100 text-green-800",
  BUYER: "bg-purple-100 text-purple-800",
  NOT_INTERESTED: "bg-gray-100 text-gray-600",
} as const;

export const DEFAULT_SETTINGS = {
  whatsappNumber: "",
  whatsappDefaultMessage: "¡Hola! Vengo de TodoTerramar y me gustaría obtener más información.",
  location: "México",
  businessHours: "Lunes a Viernes 9:00 - 18:00",
  facebook: "",
  instagram: "",
  youtube: "",
  tiktok: "",
};
